### PR TITLE
Fix Bezalel contact details

### PR DESCRIPTION
**Pull request by Bezbran**
## Overview
Fix Bezalel contact details

### CODE REVIEW

**Review by matthyx — APPROVED** [review]
thanks Bez :) I think we're going to centralize maintainers in kubescape/kubescape

**Comment by matthyx** [comment]
pls fix the DCO with `git commit --amend -s`

**Comment by Bezbran** [comment]
> thanks Bez :) I think we're going to centralize maintainers in kubescape/kubescape

Works for me, just I am not listed there for some reason.

**Comment by Bezbran** [comment]
> pls fix the DCO with `git commit --amend -s`

it fixed only the merge commit for some reason

**Pull request merged**
