### PR TITLE
fix(host-scanner): remove hostNetwork and hostPort parameters

### PR DESCRIPTION
**Pull request by alegrey91**
## Overview
This fix removes the hostNetwork and hostPort parameters from the host-scanner deployment, since we don't need them anymore.

### CODE REVIEW

**Comment by matthyx** [comment]
I am not sure we still use this one... I thought we always use the internal one? @dwertent ?

**Comment by dwertent** [comment]
@alegrey91 Please update the kubescape image version...

**Comment by dwertent** [comment]
@matthyx You might be right, I'm checking this.

**Review by dwertent — APPROVED** [review]

**Review by dwertent — APPROVED** [review]

**Pull request merged**
