### PR TITLE
docs: add troubleshooting section

### PR DESCRIPTION
**Pull request by alegrey91**
## PR Type:
Documentation

___
## PR Description:
This PR adds a troubleshooting section to the Kubescape Operator documentation. It provides a solution for a specific error related to the `node-agent` logs, which can be resolved by reinstalling the helm-chart with specific parameters.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

`charts/kubescape-operator/README.md`: A troubleshooting section has been added to the README. It provides a solution for an error related to the `node-agent` logs. The solution involves reinstalling the helm-chart with specific parameters.
</details>

___
## Overview

Related to this PR: https://github.com/kubescape/node-agent/pull/139

### CODE REVIEW

**Review by dwertent — COMMENTED** [review]
@yossi77 and I worked on a troubleshooting guide. I think we should have that guide published somewhere, maybe in the kubescape.io.
Regarding this PR, I don't think we should publish a troubleshooting only for this scenario.

/cc: @slashben @GibliX

**Comment by craigbox** [comment]
If this is meant to be user facing, it should be on (or at the least, linked to from), kubescape.io.

**Comment by GibliX** [comment]
@dwertent Are you referring to this [troubleshooting](https://hub.armosec.io/docs/installation-troubleshooting) doc?
You suggest we add the RUNC issue to this doc?

**Comment by dwertent** [comment]
@GibliX Yes

**Pull request closed without merging**
