### PR TITLE
Aks user assigned cluster support

### PR DESCRIPTION
**Pull request by rcohencyberarmor**
adding support in AKS cluster based on User Assigned Cluster.
for more information please refer to our documentation. (https://hub.armosec.io/docs/azure-aks)

### CODE REVIEW

**Comment by Bezbran** [comment]
Do we need the same for ACR integration for image scan?
If so - we need to add the support to the operator and the kube-vuln as well.

**Comment by dwertent** [comment]
True, @rcohencyberarmor please add the environment variables to the Kubevuln as well.
@Bezbran I think the Operator also authenticates with the registry.

**Comment by Bezbran** [comment]
> True, @rcohencyberarmor please add the environment variables to the Kubevuln as well. @Bezbran I think the Operator also authenticates with the registry.

So we need it in the Operator deployment as well. The question is if we need to change the code of authentication with ACR.

**Comment by dwertent** [comment]
@Bezbran I dont think we will need to change the code because the environment variables are supported by Azure.

**Review by dwertent — APPROVED** [review]

**Pull request merged**
