### PR TITLE
Profiler suggestions

### PR DESCRIPTION
**Pull request by amitschendel**
## Overview

Using the profiler suggestions I have made some remediations.

### CODE REVIEW

**Comment by matthyx** [comment]
The chart works perfectly on my kind cluster... I will try also on GKE but it looks good.
Good work @amitschendel !

**Comment by matthyx** [comment]
Works on GKE too!

**Review by matthyx — APPROVED** [review]

**Review by dwertent — APPROVED** [review]

**Comment by dwertent** [comment]
Let's wait for the [tests to pass](https://github.com/kubescape/helm-charts/actions/runs/5935241501) before merging

**Comment by amitschendel** [comment]
Looks like all tests passed @dwertent can I merge?

**Comment by dwertent** [comment]
@matthyx Can you please share what GKE you used for testing?

```
% kgp -n kubescape
NAME                              READY   STATUS             RESTARTS      AGE
gateway-7d7fdffd78-9lfmr          1/1     Running            0             32s
kollector-0                       1/1     Running            0             32s
kubescape-5fb5dfbcc9-7rdwd        1/1     Running            0             32s
kubevuln-5ddc9788b8-m84fm         1/1     Running            0             32s
node-agent-6ds7s                  0/1     CrashLoopBackOff   2 (12s ago)   32s
operator-5d4cc8dbdf-kqkfx         1/1     Running            0             32s
otel-collector-667b6f8944-cslcx   1/1     Running            0             32s
storage-7bb49bd49c-frbpm          1/1     Running            0             32s
```
Log:
```
{"level":"fatal","ts":"2023-08-24T13:56:28Z","msg":"error during validation","error":"mounting /sys/fs/bpf: permission denied"}
```
This is the `dwertent-node-agent-testing-1` cluster.

**Comment by matthyx** [comment]
I have used the `dwertent-large-node`

**Pull request merged**
